use crate::sys;

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Key {
    Esc,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Row1,
    Row2,
    Row3,
    Row4,
    Row5,
    Row6,
    Row7,
    Row8,
    Row9,
    Row0,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadDivide,
    NumpadMultiply,
    NumpadSubtract,
    NumpadAdd,
    NumpadEnter,
    NumpadDecimal,
    Printscreen,
    Scroll,
    Pause,
    Insert,
    Home,
    Pageup,
    Delete,
    End,
    Pagedown,
    Up,
    Left,
    Down,
    Right,
    Tab,
    Capslock,
    Backspace,
    Enter,
    Lctrl,
    Lwin,
    Lalt,
    Space,
    Ralt,
    Fn,
    Rmenu,
    Rctrl,
    Lshift,
    Rshift,
    Macro1,
    Macro2,
    Macro3,
    Macro4,
    Macro5,
    Oem1,
    Oem2,
    Oem3,
    Oem4,
    Oem5,
    Oem6,
    Oem7,
    Oem8,
    Oem9,
    Oem10,
    Oem11,
    Eur1,
    Eur2,
    Jpn1,
    Jpn2,
    Jpn3,
    Jpn4,
    Jpn5,
    Kor1,
    Kor2,
    Kor3,
    Kor4,
    Kor5,
    Kor6,
    Kor7,
    Invalid,
}

impl Key {
    pub fn row(self) -> u8 {
        (self.rzkey().0 >> 8) as u8
    }

    pub fn column(self) -> u8 {
        (self.rzkey().0 & 0xff) as u8
    }

    fn rzkey(self) -> sys::RZKEY {
        match self {
            Key::Esc => sys::RZKEY_ESC,
            Key::F1 => sys::RZKEY_F1,
            Key::F2 => sys::RZKEY_F2,
            Key::F3 => sys::RZKEY_F3,
            Key::F4 => sys::RZKEY_F4,
            Key::F5 => sys::RZKEY_F5,
            Key::F6 => sys::RZKEY_F6,
            Key::F7 => sys::RZKEY_F7,
            Key::F8 => sys::RZKEY_F8,
            Key::F9 => sys::RZKEY_F9,
            Key::F10 => sys::RZKEY_F10,
            Key::F11 => sys::RZKEY_F11,
            Key::F12 => sys::RZKEY_F12,
            Key::Row1 => sys::RZKEY_1,
            Key::Row2 => sys::RZKEY_2,
            Key::Row3 => sys::RZKEY_3,
            Key::Row4 => sys::RZKEY_4,
            Key::Row5 => sys::RZKEY_5,
            Key::Row6 => sys::RZKEY_6,
            Key::Row7 => sys::RZKEY_7,
            Key::Row8 => sys::RZKEY_8,
            Key::Row9 => sys::RZKEY_9,
            Key::Row0 => sys::RZKEY_0,
            Key::A => sys::RZKEY_A,
            Key::B => sys::RZKEY_B,
            Key::C => sys::RZKEY_C,
            Key::D => sys::RZKEY_D,
            Key::E => sys::RZKEY_E,
            Key::F => sys::RZKEY_F,
            Key::G => sys::RZKEY_G,
            Key::H => sys::RZKEY_H,
            Key::I => sys::RZKEY_I,
            Key::J => sys::RZKEY_J,
            Key::K => sys::RZKEY_K,
            Key::L => sys::RZKEY_L,
            Key::M => sys::RZKEY_M,
            Key::N => sys::RZKEY_N,
            Key::O => sys::RZKEY_O,
            Key::P => sys::RZKEY_P,
            Key::Q => sys::RZKEY_Q,
            Key::R => sys::RZKEY_R,
            Key::S => sys::RZKEY_S,
            Key::T => sys::RZKEY_T,
            Key::U => sys::RZKEY_U,
            Key::V => sys::RZKEY_V,
            Key::W => sys::RZKEY_W,
            Key::X => sys::RZKEY_X,
            Key::Y => sys::RZKEY_Y,
            Key::Z => sys::RZKEY_Z,
            Key::Numlock => sys::RZKEY_NUMLOCK,
            Key::Numpad0 => sys::RZKEY_NUMPAD0,
            Key::Numpad1 => sys::RZKEY_NUMPAD1,
            Key::Numpad2 => sys::RZKEY_NUMPAD2,
            Key::Numpad3 => sys::RZKEY_NUMPAD3,
            Key::Numpad4 => sys::RZKEY_NUMPAD4,
            Key::Numpad5 => sys::RZKEY_NUMPAD5,
            Key::Numpad6 => sys::RZKEY_NUMPAD6,
            Key::Numpad7 => sys::RZKEY_NUMPAD7,
            Key::Numpad8 => sys::RZKEY_NUMPAD8,
            Key::Numpad9 => sys::RZKEY_NUMPAD9,
            Key::NumpadDivide => sys::RZKEY_NUMPAD_DIVIDE,
            Key::NumpadMultiply => sys::RZKEY_NUMPAD_MULTIPLY,
            Key::NumpadSubtract => sys::RZKEY_NUMPAD_SUBTRACT,
            Key::NumpadAdd => sys::RZKEY_NUMPAD_ADD,
            Key::NumpadEnter => sys::RZKEY_NUMPAD_ENTER,
            Key::NumpadDecimal => sys::RZKEY_NUMPAD_DECIMAL,
            Key::Printscreen => sys::RZKEY_PRINTSCREEN,
            Key::Scroll => sys::RZKEY_SCROLL,
            Key::Pause => sys::RZKEY_PAUSE,
            Key::Insert => sys::RZKEY_INSERT,
            Key::Home => sys::RZKEY_HOME,
            Key::Pageup => sys::RZKEY_PAGEUP,
            Key::Delete => sys::RZKEY_DELETE,
            Key::End => sys::RZKEY_END,
            Key::Pagedown => sys::RZKEY_PAGEDOWN,
            Key::Up => sys::RZKEY_UP,
            Key::Left => sys::RZKEY_LEFT,
            Key::Down => sys::RZKEY_DOWN,
            Key::Right => sys::RZKEY_RIGHT,
            Key::Tab => sys::RZKEY_TAB,
            Key::Capslock => sys::RZKEY_CAPSLOCK,
            Key::Backspace => sys::RZKEY_BACKSPACE,
            Key::Enter => sys::RZKEY_ENTER,
            Key::Lctrl => sys::RZKEY_LCTRL,
            Key::Lwin => sys::RZKEY_LWIN,
            Key::Lalt => sys::RZKEY_LALT,
            Key::Space => sys::RZKEY_SPACE,
            Key::Ralt => sys::RZKEY_RALT,
            Key::Fn => sys::RZKEY_FN,
            Key::Rmenu => sys::RZKEY_RMENU,
            Key::Rctrl => sys::RZKEY_RCTRL,
            Key::Lshift => sys::RZKEY_LSHIFT,
            Key::Rshift => sys::RZKEY_RSHIFT,
            Key::Macro1 => sys::RZKEY_MACRO1,
            Key::Macro2 => sys::RZKEY_MACRO2,
            Key::Macro3 => sys::RZKEY_MACRO3,
            Key::Macro4 => sys::RZKEY_MACRO4,
            Key::Macro5 => sys::RZKEY_MACRO5,
            Key::Oem1 => sys::RZKEY_OEM_1,
            Key::Oem2 => sys::RZKEY_OEM_2,
            Key::Oem3 => sys::RZKEY_OEM_3,
            Key::Oem4 => sys::RZKEY_OEM_4,
            Key::Oem5 => sys::RZKEY_OEM_5,
            Key::Oem6 => sys::RZKEY_OEM_6,
            Key::Oem7 => sys::RZKEY_OEM_7,
            Key::Oem8 => sys::RZKEY_OEM_8,
            Key::Oem9 => sys::RZKEY_OEM_9,
            Key::Oem10 => sys::RZKEY_OEM_10,
            Key::Oem11 => sys::RZKEY_OEM_11,
            Key::Eur1 => sys::RZKEY_EUR_1,
            Key::Eur2 => sys::RZKEY_EUR_2,
            Key::Jpn1 => sys::RZKEY_JPN_1,
            Key::Jpn2 => sys::RZKEY_JPN_2,
            Key::Jpn3 => sys::RZKEY_JPN_3,
            Key::Jpn4 => sys::RZKEY_JPN_4,
            Key::Jpn5 => sys::RZKEY_JPN_5,
            Key::Kor1 => sys::RZKEY_KOR_1,
            Key::Kor2 => sys::RZKEY_KOR_2,
            Key::Kor3 => sys::RZKEY_KOR_3,
            Key::Kor4 => sys::RZKEY_KOR_4,
            Key::Kor5 => sys::RZKEY_KOR_5,
            Key::Kor6 => sys::RZKEY_KOR_6,
            Key::Kor7 => sys::RZKEY_KOR_7,
            Key::Invalid => sys::RZKEY_INVALID,
        }
    }
}
